export const {
	VITE_CLIENT_URL: CLIENT_URL,
	VITE_TITLE: TITLE,
	VITE_EXPIRATION_TIME_FORMAT: TIME_FORMAT,
	VITE_EXPIRATION_TIME: EXPIRATION_TIME,
	VITE_TIME_ZONE1: TIME_ZONE1,
	VITE_TIME_ZONE2: TIME_ZONE2,
} = import.meta.env;
